x-aws-vpc: "vpc-05b27ef86882e905f"
x-aws-cloudformation:
  Resources:
    Cluster:
      Type: AWS::ECS::Cluster
      Properties:
        CapacityProviders:
          - FARGATE_SPOT
        DefaultCapacityProviderStrategy:
          - CapacityProvider: FARGATE_SPOT
            Weight: 1
    FrontendService:
      Properties:
        NetworkConfiguration:
          AwsvpcConfiguration:
            Subnets:
              - subnet-092a387514379e4d0 #public subnet-1
              - subnet-03fa0d976221b86be #public subnet-2
    NginxService:
      Properties:
        NetworkConfiguration:
          AwsvpcConfiguration:
            Subnets:
              - subnet-092a387514379e4d0 #public subnet-1
              - subnet-03fa0d976221b86be #public subnet-2
    BackendService:
      Properties:
        NetworkConfiguration:
          AwsvpcConfiguration:
            Subnets:
              - subnet-092a387514379e4d0 #public subnet-1
              - subnet-03fa0d976221b86be #public subnet-2

    ########## ACM SSL Certificates ############
    LoadBalancerSSLCert:
      Type: AWS::CertificateManager::Certificate
      Properties:
        DomainName: myblog.dev.simis.com.au
        DomainValidationOptions:
          - DomainName: myblog.dev.simis.com.au
            ValidationDomain: dev.simis.com.au
          - DomainName: www.myblog.dev.simis.com.au
            ValidationDomain: dev.simis.com.au
          - DomainName: backend.myblog.dev.simis.com.au
            ValidationDomain: dev.simis.com.au
          - DomainName: www.backend.myblog.dev.simis.com.au
            ValidationDomain: dev.simis.com.au
        ValidationMethod: DNS
        SubjectAlternativeNames:
          - myblog.dev.simis.com.au
          - www.myblog.dev.simis.com.au
          - backend.myblog.dev.simis.com.au
          - www.backend.myblog.dev.simis.com.au

    ########## LoadBalancer ############
    LoadBalancer:
      Properties:
        LoadBalancerAttributes: []
        Type: application
        Subnets:
          - subnet-092a387514379e4d0 #public subnet-1
          - subnet-03fa0d976221b86be #public subnet-2
    DefaultNetwork:
      Properties:
        SecurityGroupIngress:
          - Description: HTTP IPv4
            IpProtocol: tcp
            FromPort: 80
            ToPort: 80
            CidrIp: 0.0.0.0/0
          - Description: HTTP IPv6
            IpProtocol: tcp
            FromPort: 80
            ToPort: 80
            CidrIpv6: ::/0
          - Description: HTTPS IPv4
            IpProtocol: tcp
            FromPort: 443
            ToPort: 443
            CidrIp: 0.0.0.0/0
          - Description: HTTPS IPv6
            IpProtocol: tcp
            FromPort: 443
            ToPort: 443
            CidrIpv6: ::/0

    ########## LoadBalancer Listeners ############
    NginxTCP82Listener:
      Properties:
        Protocol: HTTP

    NginxTCP82TargetGroup:
      Properties:
        Protocol: HTTP

    BackendTCP81Listener:
      Properties:
        Protocol: HTTP

    BackendTCP81TargetGroup:
      Properties:
        Protocol: HTTP

    HTTPlistener:
      DependsOn:
        - LoadBalancer
      Type: AWS::ElasticLoadBalancingV2::Listener
      Properties:
        DefaultActions:
          - Type: redirect
            RedirectConfig:
              Protocol: HTTPS
              Port: '443'
              Host: '#{host}'
              Path: /#{path}
              Query: '#{query}'
              StatusCode: HTTP_301
        LoadBalancerArn:
          Ref: LoadBalancer
        Port: 80
        Protocol: HTTP

    HTTPSListener:
      DependsOn:
        - LoadBalancerSSLCert
        - NginxTCP82TargetGroup
      Type: AWS::ElasticLoadBalancingV2::Listener
      Properties:
        Certificates:
          - CertificateArn:
              Ref:  LoadBalancerSSLCert
        DefaultActions:
          - Type: forward
            TargetGroupArn:
              Ref: NginxTCP82TargetGroup
            Order: 1
        LoadBalancerArn:
          Ref: LoadBalancer
        Port: 443
        Protocol: HTTPS

    ########## Listeners Rules ############
    BackendTCP81ListenerRule:
      DependsOn:
        - BackendTCP81TargetGroup
        - BackendTCP81Listener
      Type: AWS::ElasticLoadBalancingV2::ListenerRule
      Properties:
        Actions:
          - Type: forward
            TargetGroupArn:
              Ref: BackendTCP81TargetGroup
        Conditions:
          - Field: host-header
            HostHeaderConfig:
              Values:
                - backend.myblog.dev.simis.com.au
                - www.backend.myblog.dev.simis.com.au
        ListenerArn:
          Ref: HTTPSListener
        Priority: 1

    ########## Route53 ############
    NginxARecord:
      Type: AWS::Route53::RecordSet
      Properties:
        HostedZoneId: Z00061643K1G0XAHRO5GI
        Type: A
        Name: myblog.dev.simis.com.au
        AliasTarget:
          DNSName:
            Fn::GetAtt:
              - LoadBalancer
              - DNSName
          HostedZoneId:
            Fn::GetAtt:
              - LoadBalancer
              - CanonicalHostedZoneID
    BackendARecord:
      Type: AWS::Route53::RecordSet
      Properties:
        HostedZoneId: Z00061643K1G0XAHRO5GI
        Type: A
        Name: backend.myblog.dev.simis.com.au
        AliasTarget:
          DNSName:
            Fn::GetAtt:
              - LoadBalancer
              - DNSName
          HostedZoneId:
            Fn::GetAtt:
              - LoadBalancer
              - CanonicalHostedZoneID

services:
  nginx:
    image: 900657927515.dkr.ecr.ap-southeast-2.amazonaws.com/nextjs-nginx:latest
    deploy:
      x-aws-autoscaling:
        min: 1
        max: 2
        cpu: 65
      resources:
        limits:
          cpus: '0.5'
          memory: 1024M
    build:
      context: ./frontend/nginx
    ports:
      - "82:82"

  frontend:
    image: 900657927515.dkr.ecr.ap-southeast-2.amazonaws.com/nextjs-frontend:latest
    deploy:
      x-aws-autoscaling:
        min: 1
        max: 2
        cpu: 65
      resources:
        limits:
          cpus: '0.5'
          memory: 1024M
    build:
      context: ./frontend
    environment:
      NODE_ENV: dev

  backend:
    image: 900657927515.dkr.ecr.ap-southeast-2.amazonaws.com/nextjs-backend:latest
    deploy:
      x-aws-autoscaling:
        min: 1
        max: 2
        cpu: 65
      resources:
        limits:
          cpus: '1'
          memory: 2048M
    build:
      context: ./backend
    environment:
      NODE_ENV: dev
    ports:
      - "81:81"
